# Generated by Django 4.1.7 on 2023-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_category_student_district_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='act_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bank Account'),
        ),
    ]
