# Generated by Django 4.1.7 on 2023-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='domicile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Domicile Number'),
        ),
    ]
