# Generated by Django 4.1.7 on 2023-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_domicile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='CreatedAt'),
        ),
    ]
