# Generated by Django 4.1.7 on 2023-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='UpdatedAt'),
        ),
    ]
