# Generated by Django 4.1.7 on 2023-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
    ]
