# Generated by Django 4.1.7 on 2023-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_form',
            name='act_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bank Account'),
        ),
    ]
