# Generated by Django 4.1.7 on 2023-02-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_admission_form_act_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_form',
            old_name='act_no',
            new_name='bank',
        ),
    ]
